In [4]:
#%matplotlib inline
import numpy as np
import pandas as pd
import scipy.sparse
from sklearn import preprocessing
from sklearn.grid_search import ParameterGrid
import xgboost as xgb
import pickle
#import graphviz
import matplotlib.pyplot as plt
%matplotlib inline

Read in just the testing and training data.

In [4]:
error = pd.read_pickle('scripts/cv_results/actions_e20/search3/res1.p')
error2 = pd.read_pickle('scripts/cv_results/actions_e20/search3/res2.p')
error3 = pd.read_pickle('scripts/cv_results/actions_e20/search3/res3.p')
param = pd.read_pickle('scripts/cv_results/actions_e20/params_search3.p')
#error['mean'] = error.apply(np.mean, axis = 1)
# error = error.astype(np.float64)
# error['mean'] = error.mean(1)
# error['std'] = error.std(1)

In [12]:
e = pd.read_pickle('scripts/cv_results/actions_e20/errors_search3.p')

In [73]:
a = np.random.rand(10,12)
a

array([[ 0.93256448,  0.62660586,  0.74023929,  0.77185785,  0.8494271 ,
         0.25523737,  0.70191142,  0.92506626,  0.05066993,  0.13680322,
         0.33484532,  0.79135205],
       [ 0.73633954,  0.16127526,  0.29845055,  0.38180343,  0.00160176,
         0.74566444,  0.29698703,  0.63758913,  0.09085475,  0.19466672,
         0.81161352,  0.48289619],
       [ 0.37229718,  0.7960031 ,  0.7785618 ,  0.16127571,  0.68537243,
         0.25210643,  0.36793332,  0.5164617 ,  0.83848124,  0.92516093,
         0.73563729,  0.62202602],
       [ 0.57595445,  0.76819302,  0.97809294,  0.86944491,  0.18356635,
         0.17604503,  0.98292014,  0.3398307 ,  0.2085289 ,  0.60122573,
         0.37420214,  0.44382043],
       [ 0.31071988,  0.07375503,  0.48942148,  0.64711025,  0.30565487,
         0.72061194,  0.54664345,  0.64695656,  0.45589011,  0.41181492,
         0.18243736,  0.24911338],
       [ 0.39246987,  0.45375168,  0.10360674,  0.08689044,  0.1223181 ,
         0.82367548,  

In [150]:
pred = a.argsort(axis = 1)[:,::-1][:,0:5]

In [147]:
a.argsort(axis = 1)[:,::-1]

array([[ 0,  7,  4, 11,  3,  2,  6,  1, 10,  5,  9,  8],
       [10,  5,  0,  7, 11,  3,  2,  6,  9,  1,  8,  4],
       [ 9,  8,  1,  2, 10,  4, 11,  7,  0,  6,  5,  3],
       [ 6,  2,  3,  1,  9,  0, 11, 10,  7,  8,  4,  5],
       [ 5,  3,  7,  6,  2,  8,  9,  0,  4, 11, 10,  1],
       [ 6,  5, 11,  8,  1, 10,  0,  7,  4,  2,  3,  9],
       [ 2, 11,  0,  8,  9,  1,  7,  6,  4,  3, 10,  5],
       [ 5,  4,  7,  0,  3, 11, 10,  8,  9,  6,  2,  1],
       [ 8,  9, 11,  0,  2,  1,  7,  4,  6, 10,  5,  3],
       [ 5,  4, 11,  9,  0,  3,  7,  8,  2,  1, 10,  6]])

In [152]:
sub = pd.read_csv('submissions/actions2_e16_53n.csv')

In [162]:
sub[4::5].country.value_counts()

IT       26954
FR       14845
GB        9558
ES        7756
CA        1988
DE         336
NL         301
other      169
AU         115
PT          47
NDF         24
US           3
dtype: int64

In [138]:
label = np.array([ 7,  7, 10, 7,  10,  7 ,8])

In [164]:
pred = pred[:,1]

In [165]:
pred

array([ 7,  5,  8,  2,  3,  5, 11,  4,  9,  4])

In [173]:
np.logical_or(label == 7, label == 8)

array([ True,  True, False,  True, False,  True,  True], dtype=bool)

In [108]:
idx = np.where(label == 10)[0]

In [109]:
b[idx]

array([10,  5])

In [110]:
idx

array([2, 4])

In [111]:
len(idx)

2

In [121]:
np.sum(np.equal(b[idx], 10)) / len(idx)

0.5

In [116]:
np.sum(np.equal(b[idx], 10))

1

In [75]:
b = a.argsort(axis = 1)[:,::-1][:,0]

In [22]:
error['mean'] = error.astype(np.float).mean(axis = 1)

In [3]:
label = np.array([1, 2, 3, 1])
np.where(label == 1)

(array([0, 3]),)

In [26]:
e.loc[50:,e.columns.str.contains('valid.*mean')]

valid-error-mean0  valid-error-mean1  valid-error-mean2  valid-error-mean3
50           0.141415           0.140400           0.140647           0.140375
51           0.141493           0.140308           0.140737           0.140373
52           0.141318           0.140390           0.140692           0.140368
53           0.141280           0.140350           0.140703           0.140422
54           0.141170           0.140312           0.140748           0.140342
55           0.140960           0.140433           0.140738           0.140282
56           0.140995           0.140422           0.140677           0.140335
57           0.141025           0.140513           0.140637           0.140393
58           0.141018           0.140500           0.140587           0.140315
59           0.141055           0.140495           0.140718           0.140420
60           0.140968           0.140602           0.140647                NaN
61           0.141112           0.140652           0.140678                NaN
62           0.141093           0.140523           0.140820                NaN
63           0.141070           0.140440           0.140765                NaN
64           0.141133           0.140373           0.140767                NaN
65           0.141085           0.140318           0.140748                NaN
66           0.141090           0.140460           0.140822                NaN
67           0.141017           0.140440           0.140747                NaN
68           0.140917           0.140383           0.140750                NaN
69           0.140868           0.140478           0.140857                NaN
70           0.140897           0.140508           0.140873                NaN
71           0.140855           0.140518           0.140902                NaN
72           0.140742           0.140367           0.140937                NaN
73           0.140707           0.140413           0.140943                NaN
74           0.140702           0.140427           0.140872                NaN
75           0.140652           0.140477           0.140885                NaN
76           0.140652           0.140472           0.141020                NaN
77           0.140698           0.140598           0.140868                NaN
78           0.140728           0.140640           0.140953                NaN
79           0.140708           0.140620           0.141030                NaN
80           0.140650           0.140592                NaN                NaN
81           0.140647           0.140588                NaN                NaN
82           0.140658           0.140467                NaN                NaN
83           0.140732           0.140453                NaN                NaN
84           0.140732           0.140577                NaN                NaN
85           0.140708           0.140537                NaN                NaN
86           0.140590           0.140490                NaN                NaN
87           0.140537           0.140575                NaN                NaN
88           0.140487           0.140482                NaN                NaN
89           0.140558           0.140558                NaN                NaN
90           0.140602           0.140572                NaN                NaN
91           0.140607           0.140480                NaN                NaN
92           0.140598           0.140462                NaN                NaN
93           0.140698           0.140447                NaN                NaN
94           0.140628           0.140388                NaN                NaN
95           0.140587           0.140428                NaN                NaN
96           0.140610           0.140410                NaN                NaN
97           0.140653           0.140438                NaN                NaN
98           0.140640           0.140422                NaN                NaN
99           0.140680           0.140645              

In [11]:
param_grid = {}
param_grid['eta'] = [.16]
param_grid['max_depth'] = [6]
param_grid['subsample'] = [.7, .9]
param_grid['colsample_bytree'] = [.6]
nrounds = 80
for cnt, p in enumerate(list(ParameterGrid(param_grid)), 2):
    print p

{'subsample': 0.7, 'eta': 0.16, 'colsample_bytree': 0.6, 'max_depth': 6}
{'subsample': 0.9, 'eta': 0.16, 'colsample_bytree': 0.6, 'max_depth': 6}


In [3]:
#train_100 = pd.read_csv('Airbnb_data/train_users_2.csv', nrows = 100, index_col='id')
train_data = pd.read_csv('data/train_users_2.csv', index_col = 'id')
test_data = pd.read_csv('data/test_users.csv', index_col = 'id')
#sessions = pd.read_csv('../data/sessions.csv')
#age = pd.read_csv('Airbnb_data/age_gender_bkts.csv')
#countries = pd.read_csv('Airbnb_data/countries.csv')
all_df = pd.read_pickle('data/all_df.p')

In [163]:
for i in np.unique(test_data.first_browser):
    if i not in np.unique(train_data.first_browser):
        print i

IBrowse
Nintendo Browser
UC Browser


In [5]:
error = pd.read_pickle('scripts/cv_results.p')
params = pd.read_pickle('scripts/cv_params.p')

In [6]:
res = pd.concat([error, params], axis = 1)

In [7]:
res.sort_values(by = 'test-error-mean', axis = 0);

In [3]:
all_df = feakaggle_model(all_df)

#one hot encoding of features
print 'number of columns before one hot encoding', all_df.shape[1]
ohe_feats = ['gender', 'signup_method', 'signup_flow', 'language', 'affiliate_channel', 'affiliate_provider', 'first_affiliate_tracked', 'signup_app', 'first_device_type', 'first_browser']
all_df = pd.get_dummies(all_df, columns = ohe_feats)
print 'number of columns after one hot encoding', all_df.shape[1]

number of columns before one hot encoding 17
number of columns after one hot encoding 161


In [6]:
with open('xgbmodels/sessions_e20_25n.p', 'rb') as f:
    bst = pickle.load(f)
features = sorted(bst.get_fscore().items(), key = lambda x: x[1], reverse = True)
[(feat, all_df.columns[int(feat[1:])], score) for feat, score in features]

NameError: name 'all_df' is not defined

In [ ]:
xgb.to_graphviz(bst, num_trees=11)

In [ ]:
submission = pd.DataFrame(np.column_stack([idx, cntr]), columns = ['id', 'country'])
submission.to_csv('submissions/datebin_model.csv', index=False)